spring:
  application:
    name: payment-service
  # --- Configuration du Serveur embarqué (WebFlux) ---
  server:
    port: 8080

  # --- Configuration de la Base de Données PostgreSQL ---
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsdb
    username: triomphe
    password: maths4321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- Configuration Eureka Client (désactivé si pas de serveur Eureka) ---
  cloud:
    eureka:
      client:
        enabled: false
        service-url:
          defaultZone: http://localhost:8761/eureka
    # --- Désactiver le client Spring Cloud Config (déjà fait) ---
    config:
      enabled: false

# Configuration des APIs Orange et MTN (simulées pour le moment)
#orange-api:
#  url: http://localhost:8083/mock-orange-api/payment # URL du service Orange Money (mock ou réel)
#mtn-api:
#  url: http://localhost:8081/mock-mtn-api/payment # URL du service MTN Mobile Money (mock ou réel)
